// DECA concept-drill bank.
//
// PROVENANCE: All questions are ORIGINAL, hand-authored items that teach transferable DECA business
// concepts (identifying/addressing performance indicators, business reasoning about cost/feasibility/
// measurement, customer relations, marketing fundamentals). They are NOT reproduced from any DECA
// exam, sample role-play, evaluation form, or other protected source. Same rule as the HOSA MT and
// General Debate banks: teach the concept, never copy protected material.
//
// SCOPE: This is CONCEPT DRILLING only. It has nothing to do with the DECA role-play judging system
// (judgeDecaRoleplay, scenario/objection generation) or the blocked rubric point-split work. It only
// grades multiple-choice items and writes MasteryProgress + spaced review via recordDrillMastery.
//
// Each area maps to a DECA Skill (by slug). "deca-marketing" already exists; the other three must be
// seeded (surgical upsert). Until a skill exists, its writes are skipped gracefully (never faked).

export type DecaDrillArea = "performance-indicators" | "business-reasoning" | "customer-relations" | "marketing-fundamentals";

export const DECA_DRILL_AREAS: Array<{ id: DecaDrillArea; label: string; skillSlug: string; description: string }> = [
  { id: "performance-indicators", label: "Performance indicators", skillSlug: "deca-performance-indicators", description: "Identify what a performance indicator asks and address it explicitly." },
  { id: "business-reasoning", label: "Business reasoning", skillSlug: "deca-business-reasoning", description: "Reason about cost, feasibility, measurement, and ROI." },
  { id: "customer-relations", label: "Customer relations", skillSlug: "deca-customer-relations", description: "Handle customers and service situations professionally." },
  { id: "marketing-fundamentals", label: "Marketing fundamentals", skillSlug: "deca-marketing", description: "Apply the marketing mix, positioning, and promotion basics." }
];

export const DECA_DRILL_SKILL_SLUGS = DECA_DRILL_AREAS.map((a) => a.skillSlug);

export type DecaDrillQuestion = {
  id: string;
  area: DecaDrillArea;
  question: string;
  choices: string[];
  correctAnswer: string;
  explanation: string;
};

// Original item bank. IDs are stable so review scheduling can reference them.
export const DECA_DRILL_BANK: DecaDrillQuestion[] = [
  // --- Performance indicators ---
  { id: "pi-01", area: "performance-indicators", question: "A role-play lists the performance indicator 'Explain the nature of positive customer relations.' The BEST way to earn it is to:", choices: ["Mention customers once in passing", "Define what positive customer relations means and explain why it matters to this business, then apply it to the scenario", "List your favorite companies", "Skip it and focus on price"], correctAnswer: "Define what positive customer relations means and explain why it matters to this business, then apply it to the scenario", explanation: "Top scores come from naming the indicator, explaining the concept, AND connecting it to the specific scenario — not just referencing the topic." },
  { id: "pi-02", area: "performance-indicators", question: "Performance indicators in a DECA role-play are best described as:", choices: ["Random trivia", "The specific business skills/knowledge the judge is scoring you on", "The names of the judges", "Your personal opinions"], correctAnswer: "The specific business skills/knowledge the judge is scoring you on", explanation: "PIs are the scored competencies drawn from the event's instructional area — they tell you exactly what to demonstrate." },
  { id: "pi-03", area: "performance-indicators", question: "You're given the PI 'Describe the nature of pricing.' A response that only says 'I'd lower the price' misses points because it:", choices: ["Is too long", "States an action without explaining the pricing concept the PI asks for", "Uses the word price", "Mentions money"], correctAnswer: "States an action without explaining the pricing concept the PI asks for", explanation: "'Describe the nature of' asks you to explain the concept (how pricing works, its role), not just take an action. Address what the verb asks." },
  { id: "pi-04", area: "performance-indicators", question: "What separates a top competitor from a good one on PIs?", choices: ["Speaking faster", "Explaining each PI and connecting it to the scenario, not just naming it", "Memorizing more PIs", "Wearing a better suit"], correctAnswer: "Explaining each PI and connecting it to the scenario, not just naming it", explanation: "Good competitors mention PIs; top competitors explain them and tie them to the situation, which is where the higher scores live." },
  { id: "pi-05", area: "performance-indicators", question: "The PI verb 'Demonstrate' (e.g., 'Demonstrate active listening') asks you to:", choices: ["Define it only", "Actually show the skill in your interaction with the judge", "Skip it", "Ask the judge to do it"], correctAnswer: "Actually show the skill in your interaction with the judge", explanation: "'Demonstrate' means perform the skill live (ask a clarifying question, paraphrase back), not merely define it." },
  { id: "pi-06", area: "performance-indicators", question: "If a scenario's PI is 'Explain the concept of market segmentation,' the strongest answer:", choices: ["Names one customer", "Defines segmentation, gives an example relevant to the business, and shows how it guides the decision", "Says 'segmentation is important'", "Lists the 50 states"], correctAnswer: "Defines segmentation, gives an example relevant to the business, and shows how it guides the decision", explanation: "Define + relevant example + application to the scenario is the full pattern judges reward." },
  { id: "pi-07", area: "performance-indicators", question: "Why should you explicitly signpost the PIs you're addressing?", choices: ["It wastes time", "It helps the judge see you hit each scored indicator", "It's against the rules", "It confuses the judge"], correctAnswer: "It helps the judge see you hit each scored indicator", explanation: "Making your PI coverage visible ('To address customer relations, I would...') helps the judge award those points confidently." },
  { id: "pi-08", area: "performance-indicators", question: "A PI reads 'Determine the impact of business ethics on decision-making.' A weak answer:", choices: ["Weighs an ethical tradeoff in the scenario", "Just says 'be ethical' with no connection to a decision", "Explains how ethics changes a specific choice", "Names an ethical principle and applies it"], correctAnswer: "Just says 'be ethical' with no connection to a decision", explanation: "The PI asks for IMPACT on decision-making. A generic 'be ethical' ignores the decision link the verb requires." },
  { id: "pi-09", area: "performance-indicators", question: "The instructional area of an event tells you:", choices: ["The lunch schedule", "The family of concepts the PIs and scenario will draw from", "The judge's name", "Nothing useful"], correctAnswer: "The family of concepts the PIs and scenario will draw from", explanation: "Instructional areas (e.g., Customer Relations, Financial Analysis) frame which PIs appear — study them to prepare." },

  // M14 Global G2 Slice 5 / DECA Slice 1: performance-indicators extended 9 -> 30. Inserted INSIDE the
  // PI block, after pi-09 and before the business-reasoning block, so the grouping holds. pi-09
  // ALREADY carried its comma and mk-09 is still the final array element, so NO legacy punctuation
  // changes here — the terminal-comma boundary at mk-09 stays unexercised for a later DECA slice.
  // AUTHORING BOUNDARY: every item below wraps a LISTED performance indicator and asks what that
  // indicator requires the competitor to demonstrate in THIS scenario. Diagnostic applied to all 21:
  // remove the indicator from the stem and the question stops working.
  // Scope comes from the DECA course Module 1 lesson 3 (PIs are behaviours to DEMONSTRATE, never to
  // recite; the PI method PI -> PLAIN MEANING -> SCENARIO REQUIREMENT -> IN-CHARACTER ACTION ->
  // JUDGE-FACING EXPLANATION -> MEASUREMENT), lesson 2 (the 5-extract decode: my role, judge's role,
  // problem, PIs, constraints) and the non-negotiable PI rule (concrete decision -> business
  // reasoning -> implementation -> feasibility -> measurement).
  // NOT BUSINESS REASONING — nothing asks whether an option is feasible, what it costs, or which is
  // commercially better; br-01..br-09 own that. br-03 and br-08 in particular own generic
  // metric quality, so pi-19/pi-29/pi-30 are anchored to what the INDICATOR asked about, not to
  // whether a metric is good in the abstract.
  // NOT CUSTOMER RELATIONS — no item asks what to do with a customer; cr-01..cr-09 own that.
  // NOT MARKETING FUNDAMENTALS — marketing topics appear only as the subject an indicator points at,
  // never as knowledge tested for its own sake; mk-01..mk-09 own that.
  // B-2 IS DELIBERATELY OUT OF SCOPE. Whether to speak a PI's title aloud or weave it into the
  // conversation is taught in the curriculum as a GENUINELY CONTESTED judgment call, and legacy
  // pi-07 has a pre-existing tension with that guidance. This slice does not modify pi-07, does not
  // reinforce explicit signposting as universally correct, and does not author a contradicting item.
  // Several distractors here reject PI-name recitation as a substitute for demonstration (pi-11 D,
  // pi-13 D, pi-18 B, pi-19 C, pi-29 D) — that is the ⟨D6⟩ demonstration-vs-recitation rule, NOT a
  // ruling on speaking style. The B-2 question remains open curriculum debt. See docs/HANDOFF.md.
  // PROVENANCE: every indicator string below is an ORIGINAL PI-style prompt. None reproduces an
  // official DECA competency statement, exam item, sample role-play, or evaluation form. No official
  // PI code, cluster or list-year is named, and no per-PI exam weighting is claimed — pi-26 keys on
  // the curriculum's own point that published weighting is instructional-area level only.
  // AI-ASSISTED authoring (M14 Global G2 Slice 5 / DECA Slice 1, pi-10..pi-30), HUMAN-REVIEWED AND
  // APPROVED 2026-08-12: the repository owner personally read all 21 items in the FINAL checklist and
  // approved their answer defensibility, distractor quality, wording, curriculum fit, verb
  // interpretation, PI-method stage accuracy, scenario role/authority/constraint handling, the
  // PI/business-reasoning, PI/customer-relations and PI/marketing-fundamentals boundaries,
  // PI-essentiality under the remove-the-PI diagnostic, B-2 safety, legacy pi-07 handling, the
  // scoring and preparation claims, the measurement boundaries, legacy and new-item overlap, and
  // copyright/provenance.
  // The approved content is implementation commit b72cba239a65a1212531817ed76957179f4a816d PLUS
  // content-refinement commit 1340cdbced2df7d3761bd2ceb4432fc070909691.
  // Two items were REFINED before approval, both because they failed this file's own
  // remove-the-PI diagnostic: pi-19 named no specific indicator, so it now carries an
  // employee-retention indicator whose outcome differs from the action's stated rationale, making the
  // indicator decide what success means; and pi-30's old "win-back email to lapsed members" already
  // telegraphed retention and sat close to br-03, so the action became a targeted offer email that
  // could plausibly be judged on reach, on immediate response, or on retention — only the listed
  // indicator now picks the measure.
  // pi-28 was explicitly human-reviewed and APPROVED WITHOUT REWRITE as a PI/BR boundary case: its
  // shape looks business-reasoning-adjacent once the indicator is stripped, but its keyed axis is the
  // completeness of the PI demonstration chain, never the commercial merit of the action.
  // Approval rests on that personal human review. Claude/AI pre-screening did NOT constitute human
  // review or independent verification, and AI self-review never counts as human approval.
  // See docs/HANDOFF.md.
  { id: "pi-10", area: "performance-indicators", question: "A listed indicator reads \"Analyze the effect of a supplier delay on store operations.\" A response that only defines what a supplier delay is:", choices: ["Misses what the verb asks — analyzing means breaking the delay down into which operations it hits and how those knock into each other", "Fully satisfies the indicator, because the topic was addressed", "Fails only because it is too short", "Should instead calculate the store's total cost of the delay"], correctAnswer: "Misses what the verb asks — analyzing means breaking the delay down into which operations it hits and how those knock into each other", explanation: "'Analyze' asks you to take the situation apart — which operations are affected, in what order, and how they interact. A definition names the topic without doing any of that. Costing the delay out is a different task from analyzing it." },
  { id: "pi-11", area: "performance-indicators", question: "Two listed indicators cover the same topic: one reads \"Identify the store's primary customer group,\" the other \"Explain why that group is the store's priority.\" The difference in what you must do is:", choices: ["Identify asks you to name the right group; explain asks for the reasoning that makes it the priority", "There is no real difference — both ask for the same answer", "Identify requires more detail than explain", "Both are satisfied by stating the indicator's wording first"], correctAnswer: "Identify asks you to name the right group; explain asks for the reasoning that makes it the priority", explanation: "The verb sets the work. Naming the group satisfies the first; the second needs the reasoning behind that choice. Covering one does not automatically cover the other, even though the two usually sit together in a response." },
  { id: "pi-12", area: "performance-indicators", question: "A listed indicator reads \"Evaluate two shipping options for the store.\" A response that describes both options accurately and stops:", choices: ["Has not evaluated — an evaluation needs a judgment plus the criteria behind it", "Has evaluated, because both options were covered", "Has evaluated, as long as the descriptions are accurate", "Should have chosen the cheaper option, since cost always decides"], correctAnswer: "Has not evaluated — an evaluation needs a judgment plus the criteria behind it", explanation: "Describing is not evaluating. The indicator asks you to come down somewhere and say what you weighed — speed, reliability, cost — to get there. Which of those should dominate depends on the scenario, not on a rule." },
  { id: "pi-13", area: "performance-indicators", question: "A listed indicator reads \"Demonstrate a procedure for handling a damaged shipment.\" The competitor gives a textbook-accurate definition of damage-claim procedure and moves on. This response:", choices: ["Shows the knowledge but never performs the procedure the indicator asks to see", "Is complete, because the definition was accurate", "Fails because the definition was wrong", "Fails because the indicator was not named aloud first"], correctAnswer: "Shows the knowledge but never performs the procedure the indicator asks to see", explanation: "Accuracy is not the problem — the verb is. 'Demonstrate' asks you to walk the steps in the scenario rather than define them. This is the mirror image of answering with an action where the indicator asked you to describe a concept." },
  { id: "pi-14", area: "performance-indicators", question: "One listed indicator reads \"Describe the store's return policy\"; another reads \"Apply the return policy to a customer's request.\" The strongest response:", choices: ["Explains what the policy is for the first, and works through the customer's actual request for the second", "Uses the same explanation for both, since the topic is identical", "Handles only the second, because applying includes describing", "Handles only the first, because describing is the harder task"], correctAnswer: "Explains what the policy is for the first, and works through the customer's actual request for the second", explanation: "Shared topic, different demonstrations. One asks what the policy is; the other asks you to run it against a live request. Doing one well leaves the other undemonstrated, because the verbs call for different things." },
  { id: "pi-15", area: "performance-indicators", question: "A listed indicator reads \"Explain the nature of staff-morale factors in a retail setting.\" Before building your response, the most useful first step is to restate it as:", choices: ["\"What makes staff here feel good or bad about this job, and why does that matter to the store?\"", "\"I will now be addressing staff morale.\"", "\"Staff morale is an important business topic.\"", "\"Morale should be kept as high as possible at all times.\""], correctAnswer: "\"What makes staff here feel good or bad about this job, and why does that matter to the store?\"", explanation: "Putting a formal indicator into plain words is what makes the rest of the response possible — you cannot demonstrate something you have not yet pinned down. Announcing the topic or calling it important restates nothing." },
  { id: "pi-16", area: "performance-indicators", question: "You understand the indicator \"Explain the nature of inventory control.\" The scenario is a food truck with one small refrigerator and daily deliveries. What this scenario makes the indicator require is:", choices: ["Inventory control as it works under tight storage and daily turnover, not inventory control in general", "A general definition of inventory control, since the concept does not change", "A calculation of the truck's optimal order quantity", "A list of the inventory systems available on the market"], correctAnswer: "Inventory control as it works under tight storage and daily turnover, not inventory control in general", explanation: "The same indicator asks for different things in different scenarios. Here the constraints — one refrigerator, daily deliveries — are what the explanation has to be about. Running the order-quantity numbers is a separate task." },
  { id: "pi-17", area: "performance-indicators", question: "You are the assistant manager. The listed indicator is \"Demonstrate how to resolve a scheduling conflict between two employees.\" Which response stays inside your role and shows the skill?", choices: ["Bring both employees together, hear each constraint, and propose a swap you have the authority to approve", "Explain that scheduling conflicts should generally be resolved fairly", "Dismiss the employee who complained and rebuild the schedule", "Tell the judge you would send it to the district director to decide"], correctAnswer: "Bring both employees together, hear each constraint, and propose a swap you have the authority to approve", explanation: "The indicator asks to see the skill, and the scenario gives you a role with limits. A general principle demonstrates nothing, dismissing someone exceeds an assistant manager's authority, and handing it upward avoids the demonstration altogether." },
  { id: "pi-18", area: "performance-indicators", question: "You have decided to move a new display to the store entrance. The listed indicator is \"Explain the role of product placement in sales.\" The strongest thing to say next is:", choices: ["Why entrance placement drives impulse purchases, and why that fits a store whose foot traffic peaks at lunch", "That you have now addressed the product-placement indicator", "That product placement is a well-known part of retail marketing", "That the display simply looks better near the entrance"], correctAnswer: "Why entrance placement drives impulse purchases, and why that fits a store whose foot traffic peaks at lunch", explanation: "The judge scores the reasoning, not the move on its own. Tying the placement principle to this store's traffic pattern is what shows the indicator was understood and used. Reporting that you covered it adds nothing to the demonstration." },
  { id: "pi-19", area: "performance-indicators", question: "The listed indicator is \"Explain the nature of employee retention in a small business.\" You decide to give every associate a monthly twenty-minute one-on-one with the manager, because associates say they have no way to raise problems, and you set out who runs the meetings and when. Against a complete demonstration of that indicator, the response:", choices: ["Has not finished — nothing in it would show whether associates actually stay, which is what this indicator is about", "Is complete, because the action, its reason and its rollout are all present", "Is incomplete because the indicator was not restated at the end", "Is incomplete because a monthly check-in is too infrequent to help"], correctAnswer: "Has not finished — nothing in it would show whether associates actually stay, which is what this indicator is about", explanation: "A demonstration carries the action through to how success gets checked, and the indicator decides what success even means here. The reason given is about being heard, but the listed competency is retention — so the check has to be about people staying, not about how the meetings felt. Where a scenario genuinely offers nothing to measure, say so rather than inventing a number." },
  { id: "pi-20", area: "performance-indicators", question: "A scenario reads: \"You are the events coordinator for a community gym. Membership fell 12% last quarter. Your budget is $4,000. The judge is the gym owner. You will be evaluated on: explaining the nature of customer retention, and describing promotional planning.\" The listed indicators are:", choices: ["Explaining the nature of customer retention, and describing promotional planning", "The 12% membership drop and the $4,000 budget", "Being the events coordinator, and the owner being the judge", "Everything in the scenario, since all of it is scored"], correctAnswer: "Explaining the nature of customer retention, and describing promotional planning", explanation: "The indicators are the competencies you are evaluated on. The membership drop is the problem, the budget is a constraint, and the two roles say who is speaking — all necessary context, none of it the scored list." },
  { id: "pi-21", area: "performance-indicators", question: "In that same gym scenario, the $4,000 budget is:", choices: ["A constraint on how you demonstrate the indicators, not something scored on its own", "A listed indicator you must address directly", "Irrelevant, because it is not one of the indicators", "The most heavily weighted part of the evaluation"], correctAnswer: "A constraint on how you demonstrate the indicators, not something scored on its own", explanation: "Constraints shape the response — a promotional plan has to fit $4,000. But staying inside the budget is not itself a scored competency, and ignoring it would make the demonstration unrealistic." },
  { id: "pi-22", area: "performance-indicators", question: "You have ten minutes of prep and three listed indicators. The best use of that time is to:", choices: ["Work out a usable line on each indicator, then deepen whichever still looks thinnest", "Perfect your answer to the first indicator and improvise the other two", "Give each indicator exactly 200 seconds regardless of difficulty", "Skip prep and read the indicators for the first time during the role-play"], correctAnswer: "Work out a usable line on each indicator, then deepen whichever still looks thinnest", explanation: "Every listed indicator is being scored, so leaving one with no plan costs more than polishing another. Splitting the clock into equal fixed blocks is its own kind of rigid — some indicators need more thought than others." },
  { id: "pi-23", area: "performance-indicators", question: "The listed indicator is \"Explain the nature of customer retention.\" The competitor delivers an impressive break-even analysis instead and touches retention only in passing. Against that listed indicator, the analysis:", choices: ["Does not substitute — strong extra work is not what this indicator is scoring", "Fully compensates, because the analysis was more advanced", "Is worthless, because anything unlisted is wasted effort", "Guarantees a lower total result than saying nothing at all"], correctAnswer: "Does not substitute — strong extra work is not what this indicator is scoring", explanation: "Extra strength can make the interaction better and is not wasted. It simply cannot stand in for the competency that was actually listed, which still has to be demonstrated." },
  { id: "pi-24", area: "performance-indicators", question: "You know your event's instructional area but not which indicators will appear. The most useful preparation is to:", choices: ["Learn the instructional area's core concepts and practice decoding unfamiliar indicators quickly", "Try to obtain the exact indicator list before the event", "Memorize responses to last year's indicators and reuse them", "Skip preparing, since the indicators are unknown"], correctAnswer: "Learn the instructional area's core concepts and practice decoding unfamiliar indicators quickly", explanation: "You cannot prepare the exact wording, but you can prepare the ground it comes from — the area's concepts — and the skill of turning an indicator you have never seen into a response on the spot." },
  { id: "pi-25", area: "performance-indicators", question: "Three indicators are listed. The competitor gives an outstanding response to the first and never returns to the other two. This is weaker than a solid response to all three because:", choices: ["Each listed indicator is being scored, and two of them went undemonstrated", "Long responses are penalized", "The first indicator is always worth the least", "Judges stop listening after the first indicator"], correctAnswer: "Each listed indicator is being scored, and two of them went undemonstrated", explanation: "Depth is worth having, but not at the price of leaving scored competencies untouched. Covering all three meaningfully demonstrates more of what was actually listed." },
  { id: "pi-26", area: "performance-indicators", question: "A student plans to spend most of their study time on one indicator, believing it carries a higher published exam weight than the others. The problem with that plan is:", choices: ["Published weighting is given for instructional areas, not for individual indicators", "All indicators are always weighted exactly equally", "Studying any single indicator is never useful", "The weights are changed during the competition itself"], correctAnswer: "Published weighting is given for instructional areas, not for individual indicators", explanation: "There is no per-indicator weight to optimize against — the published figures describe instructional areas. Studying the area those indicators are drawn from is the version of this plan that actually works." },
  { id: "pi-27", area: "performance-indicators", question: "The listed indicator is \"Explain the nature of pricing strategy.\" A poised competitor accurately defines penetration, skimming and cost-plus pricing in full sentences, and never says what this store should do. The response:", choices: ["Is fluent knowledge without the decision that would demonstrate the indicator in this scenario", "Is complete, because all three strategies were explained correctly", "Is weak because the definitions were inaccurate", "Is weak because it used technical vocabulary"], correctAnswer: "Is fluent knowledge without the decision that would demonstrate the indicator in this scenario", explanation: "Polish is not demonstration. Nothing said here is wrong, and it beats silence — but the indicator lives inside a scenario, and this response never arrives at a choice for that store." },
  { id: "pi-28", area: "performance-indicators", question: "The listed indicator is \"Explain the nature of employee training.\" Which response demonstrates it most completely?", choices: ["Run a two-hour Saturday session because new hires are erroring on returns, cover the three most-missed steps, cost it at one trainer's overtime, and re-check return errors in a month", "Explain why training matters, describe a two-hour Saturday session, and note that new hires are erroring on returns", "Explain why training matters and recommend investing more in employee development", "Describe several common training formats and note that each suits a different kind of business"], correctAnswer: "Run a two-hour Saturday session because new hires are erroring on returns, cover the three most-missed steps, cost it at one trainer's overtime, and re-check return errors in a month", explanation: "Only the first runs the whole way: a concrete decision, the reason for it, how it is carried out, whether it is affordable, and how success gets checked. The second is genuinely developed but never costs it or checks it; the last two never reach a decision at all." },
  { id: "pi-29", area: "performance-indicators", question: "The listed indicator is \"Explain the nature of customer-flow management in a retail store.\" A competitor decides to open a second checkout lane at peak hours, explains that queue length is driving walkouts, and sets out the staffing change that makes it happen. Against a complete demonstration of that indicator, what is missing is:", choices: ["Any check on whether the change actually reduced walkouts", "The reason the change was chosen", "The decision itself", "A closing statement that the indicator has been addressed"], correctAnswer: "Any check on whether the change actually reduced walkouts", explanation: "Decision, reasoning and implementation are all present, so this response is genuinely developed against the indicator. It stops one step short, at the point where you would name what you would watch to know it worked." },
  { id: "pi-30", area: "performance-indicators", question: "The listed indicator is \"Explain the nature of customer retention.\" You decide to send a targeted offer email to gym members who have not visited in sixty days. Which result best tells the judge whether that action succeeded FOR THIS INDICATOR?", choices: ["The share of those members who return and are still attending three months later", "The percentage of recipients who opened the email", "How many offer codes were redeemed in the first week", "The gym's total revenue for the year"], correctAnswer: "The share of those members who return and are still attending three months later", explanation: "The same email could be judged on reach, on immediate response, or on whether people came back and stayed — the listed indicator is what decides which. This one is about retention, so the evidence has to be members returning and remaining. Open rate measures reach, redemptions measure the short-term promotional response, and annual revenue moves for a dozen unrelated reasons. Each of those is a respectable business metric; they simply answer a different question from the one this indicator asks." },

  // --- Business reasoning (cost / feasibility / measurement / ROI) ---
  { id: "br-01", area: "business-reasoning", question: "A judge asks 'What will this cost us?' The strongest answer includes:", choices: ["'It'll be worth it.'", "A concrete cost figure or range AND how it compares to the expected benefit", "'Costs don't matter here.'", "'I'm not sure.'"], correctAnswer: "A concrete cost figure or range AND how it compares to the expected benefit", explanation: "Business reasoning pairs a cost estimate with the return — cost alone or a vague reassurance doesn't answer the decision." },
  { id: "br-02", area: "business-reasoning", question: "ROI (return on investment) is best explained as:", choices: ["Total revenue", "The gain from an investment relative to its cost", "The number of employees", "The price of the product"], correctAnswer: "The gain from an investment relative to its cost", explanation: "ROI = (benefit − cost) / cost. It answers whether the payoff justifies the spend, not just how big revenue is." },
  { id: "br-03", area: "business-reasoning", question: "You propose a loyalty program. The judge asks how you'd MEASURE success. Best answer:", choices: ["'People will like it.'", "Track repeat-purchase rate and retention before vs. after, with a target", "'We'll just know.'", "'Sales always go up.'"], correctAnswer: "Track repeat-purchase rate and retention before vs. after, with a target", explanation: "Measurement means naming a specific metric, a baseline comparison, and a target — not a feeling or an assumption." },
  { id: "br-04", area: "business-reasoning", question: "A recommendation is 'feasible' when it:", choices: ["Sounds impressive", "Can realistically be done with the business's resources and constraints", "Is the most expensive option", "Is what a competitor did"], correctAnswer: "Can realistically be done with the business's resources and constraints", explanation: "Feasibility is about whether the plan fits the real budget, staff, time, and capabilities — not ambition or imitation." },
  { id: "br-05", area: "business-reasoning", question: "The judge says 'We tried something like this and it failed.' The best response:", choices: ["Repeat your original pitch louder", "Acknowledge it, then explain what's different about your approach and how you'd de-risk it", "Give up on the idea", "Say the last team was incompetent"], correctAnswer: "Acknowledge it, then explain what's different about your approach and how you'd de-risk it", explanation: "Strong reasoning engages the objection: what changed, and how you'd reduce the risk this time. Volume and blame don't." },
  { id: "br-06", area: "business-reasoning", question: "'Break-even' is the point where:", choices: ["Profit is highest", "Total revenue equals total costs", "You run out of inventory", "The store closes"], correctAnswer: "Total revenue equals total costs", explanation: "Break-even is where you've covered costs and start making profit beyond it — a key feasibility/measurement concept." },
  { id: "br-07", area: "business-reasoning", question: "Which best shows you considered a TRADEOFF?", choices: ["'My plan has no downsides.'", "'This raises upfront cost, but the higher retention pays it back within a quarter.'", "'Everything will be perfect.'", "'Cost is irrelevant.'"], correctAnswer: "'This raises upfront cost, but the higher retention pays it back within a quarter.'", explanation: "Acknowledging a real cost and explaining why the benefit outweighs it demonstrates mature business judgment." },
  { id: "br-08", area: "business-reasoning", question: "A judge asks for a metric to track a marketing campaign. The WEAKEST answer is:", choices: ["Conversion rate", "Cost per acquisition", "'Vibes'", "Return on ad spend"], correctAnswer: "'Vibes'", explanation: "Conversion rate, cost per acquisition, and ROAS are measurable; 'vibes' is not a metric and can't be tracked or targeted." },
  { id: "br-09", area: "business-reasoning", question: "Prioritizing recommendations by impact and effort helps because it:", choices: ["Impresses with jargon", "Directs limited resources to the highest-value, achievable actions first", "Guarantees success", "Avoids making decisions"], correctAnswer: "Directs limited resources to the highest-value, achievable actions first", explanation: "Impact/effort prioritization is practical reasoning: do the high-impact, feasible things first when resources are limited." },

  // M14 Global G2 Slice 6 / DECA Slice 2: business-reasoning extended 9 -> 30. Inserted INSIDE the BR
  // block, after br-09 and before the customer-relations block. BR is a MIDDLE block, so br-09 already
  // carried its comma and NO legacy punctuation changed here either; mk-09 is still the final array
  // element and still comma-less, so the DECA terminal-comma boundary stays unexercised.
  // Scope comes from the DECA course Module 2 lessons 9-12: attaching the "because" (revenue, cost,
  // retention, loyalty, brand, risk), implementation and feasibility (who does what by when with what
  // resources), cost/risk/tradeoffs (what the plan costs and what could go wrong), and measuring
  // success (the one or two metrics the business would actually watch).
  // ⟨D7 — LABELING HONESTY⟩ PROBLEM -> RECOMMENDATION -> BUSINESS REASON -> IMPLEMENTATION ->
  // MEASUREMENT is COMPETEREADY'S TEACHING SCAFFOLD, NOT official DECA terminology. No item below
  // claims DECA names it, that judges require those five stages, or that it is an official scoring
  // structure. br-29's explanation says so outright.
  // ⟨B-8 — CONSTRAINED⟩ Implementation and measurement make a recommendation more concrete, feasible
  // and testable, but the curriculum research did NOT establish that they reliably separate top
  // scores and NO score improvement is promised. No item claims better/higher scores, more points, or
  // that competitors using them beat competitors who do not. B-8 is an AUTHORING GUARDRAIL here — it
  // is deliberately NOT the learner skill of any question.
  // BR BOUNDARY: every item asks why a recommendation is sound, feasible, affordable, survivable or
  // measurable ON THE SUPPLIED FACTS. Inverse-PI diagnostic applied to all 21: none needs a listed
  // performance indicator, and none would work better with one.
  // NOT PERFORMANCE INDICATORS — nothing decodes a verb, judges PI completeness, handles a PI title,
  // or matches a metric to a NAMED competency; pi-12/16/19/28/29/30 own that. br-26 in particular is
  // driven by the scenario's stated business problem, never by an indicator, which is what keeps it
  // clear of pi-30.
  // NOT CUSTOMER RELATIONS — no item asks what to say or do with a customer; cr-01..cr-09 own that.
  // Where customers appear they are an economic fact (retention windows, trade collection, queue
  // abandonment), and every item survives removing the interaction itself.
  // NOT MARKETING FUNDAMENTALS — no item asks what a marketing term means; mk-01..mk-09 own that.
  // Marketing decisions appear only as things to be justified, costed, staffed or measured.
  // FACT SUFFICIENCY: every number needed is in its stem. Arithmetic is deliberately transparent
  // (12 x $85, 4 x $1,100 + $500, $4,000 / $1,500) and never the primary skill. No named framework is
  // introduced that project source does not support — no fixed vs variable cost, no opportunity cost,
  // no leading vs lagging metrics, no stakeholder or resource-allocation framework, and br-19 works
  // out an order from stated dependencies rather than naming a sequencing method.
  // AI-ASSISTED authoring (M14 Global G2 Slice 6 / DECA Slice 2, br-10..br-30) — HUMAN CONTENT REVIEW
  // OUTSTANDING. See docs/HANDOFF.md. AI self-review does NOT count as human review.
  { id: "br-10", area: "business-reasoning", question: "A cafe closes at 4pm. Staff are already scheduled and paid until 6pm, and the manager logs 30 to 40 people a week asking about evening hours. Which reason best explains how staying open until 7pm would affect revenue?", choices: ["It sells to demand that is already turning up and asking, during hours the cafe is largely paying for anyway", "Longer hours make the cafe look more professional", "Competitors in the area also stay open later", "Evening customers usually spend more than morning customers"], correctAnswer: "It sells to demand that is already turning up and asking, during hours the cafe is largely paying for anyway", explanation: "The revenue case rests on the two facts given: demand that already shows up asking, and staffing the cafe is paying for until 6pm regardless. Appearance and what competitors do are not revenue reasons, and nothing here says evening customers spend more — that would be an assumption rather than a because." },
  { id: "br-11", area: "business-reasoning", question: "A print shop pays an $85 rush-delivery surcharge on about 12 orders a month, because client artwork arrives too late to schedule normally. Which reason best supports requiring artwork three business days ahead?", choices: ["It removes the cause of a surcharge currently costing about $1,020 a month", "It makes the shop's process look more organized", "Clients generally prefer having clear deadlines", "It would let the shop raise its prices"], correctAnswer: "It removes the cause of a surcharge currently costing about $1,020 a month", explanation: "The cost case is concrete: 12 orders at $85 is roughly $1,020 a month, and late artwork is what triggers every one of them. Tidiness and client preference are not cost reasons, and raising prices is a different decision these facts do not support." },
  { id: "br-12", area: "business-reasoning", question: "At a gym, 40% of all cancellations happen in a member's first 90 days, and members who get past 90 days stay about two more years on average. Which reason best supports adding a coached check-in at day 30?", choices: ["It targets the window where most cancellations happen, and clearing that window is worth about two more years of membership", "Members enjoy getting attention from staff", "Check-ins are common practice at gyms", "It gives staff something to do during quiet hours"], correctAnswer: "It targets the window where most cancellations happen, and clearing that window is worth about two more years of membership", explanation: "Both numbers do the work: cancellation risk is concentrated early, and getting past it is worth a long tail of membership. Enjoyment, industry habit and staff scheduling are not retention reasons — and note this is the business case for the check-in, not advice on what to say during one." },
  { id: "br-13", area: "business-reasoning", question: "A bakery buys the filling for its signature product from one supplier, who had two multi-week outages last year. A second supplier will sell the same filling for 8% more. Which reason best supports splitting the order between both?", choices: ["It limits the risk that another outage stops production of the bakery's signature product entirely", "Paying more always signals higher quality", "Two suppliers are always safer than one", "The 8% increase will be offset by higher sales"], correctAnswer: "It limits the risk that another outage stops production of the bakery's signature product entirely", explanation: "The risk is documented rather than imagined — two outages already happened, and the product at stake is the signature line. The second and third options state rules these facts do not support, and nothing here suggests sales will rise to cover the 8%." },
  { id: "br-14", area: "business-reasoning", question: "A competitor says: \"I recommend the store add a weekend delivery service, staffed by two drivers, launching next month.\" Judged as business reasoning, this is:", choices: ["A specific recommendation with no reason tied to anything in the situation", "Complete, because it names the staffing and the timing", "Weak because it is too short", "Weak because delivery is rarely profitable"], correctAnswer: "A specific recommendation with no reason tied to anything in the situation", explanation: "Scope, staffing and timing make this concrete, not justified — nothing says what problem it solves or why it is worth doing at this store. Length is not the issue, and 'delivery is rarely profitable' is a claim the scenario never establishes." },
  { id: "br-15", area: "business-reasoning", question: "A store plans to phone every customer whose order was delayed. The manager covers the sales floor alone from 9 to 5; two part-time associates work 4 to 8 in the evening. Which implementation assigns the work to someone who can actually do it?", choices: ["The evening associates make the calls between 4 and 8, when two people are on shift", "The manager makes the calls during the day", "Whoever has time makes the calls", "Customers are asked to phone the store instead"], correctAnswer: "The evening associates make the calls between 4 and 8, when two people are on shift", explanation: "Only the evening shift has a second person free to step away from the floor. Assigning it to the manager ignores that they are alone until 5, 'whoever has time' names no owner at all, and pushing the call back onto the customer abandons the plan rather than implementing it." },
  { id: "br-16", area: "business-reasoning", question: "A garden center's busiest six weeks run from late April to early June. Retraining every employee on the new till system takes each person one full shift off the floor. When should the retraining run?", choices: ["Before late April, so nobody is off the floor during the busiest six weeks", "During the busy period, when the tills get the most use", "Immediately, because sooner is always better", "After early June, once staff have used the old system longer"], correctAnswer: "Before late April, so nobody is off the floor during the busiest six weeks", explanation: "The stated constraint is that training removes a person from the floor for a whole shift, and the peak is named. Training during the peak spends staff exactly when they are least available, 'sooner is always better' is a rule these facts do not need, and waiting until June runs the peak on untrained staff — the very thing the training exists to prevent." },
  { id: "br-17", area: "business-reasoning", question: "A shop has $1,200 and six staff-hours available for a one-week promotion. Which plan can actually be carried out with those resources?", choices: ["A $900 print run plus a two-hour in-store setup", "A $1,150 print run plus eight hours of in-store demonstrations", "A $2,000 radio buy plus a one-hour setup", "A $400 flyer drop plus twenty hours of staffed sampling"], correctAnswer: "A $900 print run plus a two-hour in-store setup", explanation: "Only the first fits both limits at once. The second is inside budget but two hours over on staffing, the third is well over budget, and the fourth is cheap but needs more than three times the hours available. Feasibility means fitting every stated constraint, not just the easiest one." },
  { id: "br-18", area: "business-reasoning", question: "A business has $3,000 left in its marketing budget. A team proposes four billboards at $1,100 each for one month, plus $500 of design work. On the numbers given, the proposal:", choices: ["Cannot be executed as described — it needs $4,900 against a $3,000 budget", "Is feasible, because billboards are a standard channel", "Is feasible as long as the design work is done well", "Cannot be judged without knowing the expected return"], correctAnswer: "Cannot be executed as described — it needs $4,900 against a $3,000 budget", explanation: "Four billboards at $1,100 is $4,400, and $500 of design takes it to $4,900 — $1,900 more than exists. Whether billboards are a standard channel or the design is good does not change the arithmetic, and the return question only arises once a plan is affordable at all." },
  { id: "br-19", area: "business-reasoning", question: "A restaurant wants to launch online ordering next week. The kitchen ticket printer is not yet connected to the ordering system, and no one has been trained on it. Which order of steps works on these facts?", choices: ["Connect the printer, train the staff, then open ordering to customers", "Open ordering, then connect the printer and train staff as orders arrive", "Train the staff, open ordering, then connect the printer", "Open ordering and keep taking phone orders in case it fails"], correctAnswer: "Connect the printer, train the staff, then open ordering to customers", explanation: "The stated facts set the order: orders cannot reach the kitchen until the printer is connected, and staff cannot work a system they have not been trained on. Two of the alternatives go live before the kitchen can receive an order at all, and the last adds a fallback without fixing either gap." },
  { id: "br-20", area: "business-reasoning", question: "A shop is switching suppliers. The new supplier uses a different invoice format, delivers Tuesdays instead of Mondays, sits twenty minutes further away, and uses different product codes — so all 400 shelf tags must be relabeled by hand. The material cost of the switch is:", choices: ["The staff time to relabel 400 shelf tags", "Learning the new invoice format", "Moving the delivery day from Monday to Tuesday", "The supplier's extra twenty minutes of distance"], correctAnswer: "The staff time to relabel 400 shelf tags", explanation: "Three of these are one-off adjustments that consume almost nothing once made. Relabeling 400 tags by hand is the one that eats real staff hours. A cost is what actually consumes money, time or capacity — not everything that feels like a change." },
  { id: "br-21", area: "business-reasoning", question: "A hardware store plans to close on Sundays to save staffing. Sunday is only 6% of weekly sales, but the store's bulk trade customers collect their orders on Sunday because their own sites are shut that day. The realistic downside is:", choices: ["Trade customers lose their only collection day, which puts more than the 6% at risk", "The store will look less committed to the community", "Every plan carries some risk", "Staff will be unhappy about losing Sunday shifts"], correctAnswer: "Trade customers lose their only collection day, which puts more than the 6% at risk", explanation: "The scenario ties Sunday specifically to trade collection, so the exposure runs past the headline 6% — those customers' whole ordering pattern depends on that day. Community perception and staff feeling are not established here, and 'every plan carries some risk' is true of anything, which makes it useless as analysis." },
  { id: "br-22", area: "business-reasoning", question: "A retailer is considering extending its returns window from 14 days to 60. The short window generates about nine customer complaints a week, and a longer window means more items come back and more staff time processing them. Which statement states the tradeoff accurately?", choices: ["A longer window should cut the weekly complaints, at the price of more returns to process and the staff time that takes", "A longer window is better, because customer satisfaction matters most", "A longer window costs more to run, so it is not worth doing", "A longer window has no real downside if it is communicated clearly"], correctAnswer: "A longer window should cut the weekly complaints, at the price of more returns to process and the staff time that takes", explanation: "A tradeoff names both sides: what improves and what it costs. Two of the alternatives name only one side and then declare a winner, and the last denies a cost the scenario states outright. Which way to decide depends on how the two compare here — the statement's job is to put both on the table." },
  { id: "br-23", area: "business-reasoning", question: "A bakery wants to start delivering. The risk it has identified is that nobody knows whether the demand is there, and the van it would need comes on a 24-month lease. Which change reduces that specific risk while keeping the plan alive?", choices: ["Run deliveries for eight weeks with a van hired by the week, then decide on the lease", "Drop the delivery idea", "Sign the lease and advertise heavily to make sure demand appears", "Buy a van outright instead of leasing one"], correctAnswer: "Run deliveries for eight weeks with a van hired by the week, then decide on the lease", explanation: "The risk is a long commitment made before the demand is known, so the fix is a short reversible version that produces the missing information. Dropping the plan abandons it rather than de-risking it, advertising harder does not shorten the commitment, and buying outright deepens it." },
  { id: "br-24", area: "business-reasoning", question: "A caterer is choosing a card terminal. Terminal A costs $22 a month more but settles takings the same day; Terminal B is cheaper but settles after three days. The caterer has paid suppliers late twice this quarter because cash arrived after the invoices were due. On these facts:", choices: ["The $22 is a genuine cost, but same-day settlement addresses the cash-flow problem the business actually has", "Terminal B wins, because it is cheaper every month", "The $22 difference is irrelevant to a business decision", "Terminal A wins, because faster is always better"], correctAnswer: "The $22 is a genuine cost, but same-day settlement addresses the cash-flow problem the business actually has", explanation: "The cheaper option really is cheaper, and saying so is not wrong — it just is not what decides this one. The scenario names a live cash-flow failure that three-day settlement would keep reproducing. Dismissing the $22 as irrelevant ignores a real cost, and 'faster is always better' is a rule these facts do not need." },
  { id: "br-25", area: "business-reasoning", question: "A cafe launches a loyalty app to get customers coming back more often. It can pull downloads, app-store rating, points issued, redemption rate, repeat-visit rate, social mentions and email open rate. The most useful way to measure success is:", choices: ["Repeat-visit rate, with redemption rate alongside it", "All seven, so that nothing is missed", "Downloads, because they show how many people have the app", "App-store rating, because it shows what customers think"], correctAnswer: "Repeat-visit rate, with redemption rate alongside it", explanation: "The stated goal is customers coming back more often, so repeat visits is the measure, with redemptions showing the app is what is driving it. Tracking everything buries the signal rather than protecting it, downloads count installs rather than returns, and a rating measures opinion. Two is not a rule — it is simply how many of these speak to this goal." },
  { id: "br-26", area: "business-reasoning", question: "A shop's stated problem is that customers join the lunchtime queue and then leave without buying. It adds a second till. Which measure tracks whether that problem improved?", choices: ["The share of lunchtime customers who join the queue and leave before paying", "Total lunchtime sales", "Average transaction value", "Transactions processed per hour"], correctAnswer: "The share of lunchtime customers who join the queue and leave before paying", explanation: "The problem was named precisely — people giving up in the queue — so the measure has to track exactly that. Total sales and transaction counts move for reasons that have nothing to do with abandonment, and average value says nothing about who walked away. Here it is the stated business problem that picks the metric." },
  { id: "br-27", area: "business-reasoning", question: "A manager reports that the store's online conversion rate was 2.4% last month. On its own, that number is hard to act on because:", choices: ["There is nothing to compare it against — earlier months, other stores, or a target", "2.4% is too low for any business", "Conversion rate is not a real metric", "One month is never long enough to measure anything"], correctAnswer: "There is nothing to compare it against — earlier months, other stores, or a target", explanation: "A single figure describes a moment without saying whether it is rising, falling or normal. Set beside last quarter's number or an agreed target, the same 2.4% becomes readable. Calling it too low judges against a standard the scenario never gives, and the other two dismiss a legitimate measure." },
  { id: "br-28", area: "business-reasoning", question: "A food truck wants to know whether its new menu item is working. It has a card terminal that itemizes every sale and a paper tally at the window; it has no loyalty scheme and no customer accounts. Which measure is realistic for it to collect?", choices: ["Units of the new item sold per service, from the itemized card takings", "The share of buyers who are trying the item for a second time", "How the item's buyers rate it against competitors' versions", "The lifetime value of customers who order the item"], correctAnswer: "Units of the new item sold per service, from the itemized card takings", explanation: "The truck can already count what it sells. The other three all require recognizing individual customers over time or surveying them, and nothing in its systems does either. A measure the business cannot actually collect is not one it can use, however relevant it sounds." },
  { id: "br-29", area: "business-reasoning", question: "A bookshop's problem is that school-holiday footfall is high but conversion is low. Which response develops the strongest business case?", choices: ["Run a staffed recommendation table in the children's section over the holidays, because browsing families need help choosing; one associate covers it 11 to 3 on the existing rota, and we compare children's-section conversion with last holiday", "Run a staffed recommendation table in the children's section over the holidays, because browsing families need help choosing", "Run a staffed recommendation table, and track children's-section conversion", "We should improve the experience for families visiting during the holidays"], correctAnswer: "Run a staffed recommendation table in the children's section over the holidays, because browsing families need help choosing; one associate covers it 11 to 3 on the existing rota, and we compare children's-section conversion with last holiday", explanation: "The first names the action, why it addresses the stated problem, who staffs it and when, and what would show it worked. The second stops at the reason, the third skips both the reason and the staffing, and the fourth never reaches a recommendation. Building a case this way is CompeteReady's teaching method rather than official DECA terminology, and it is not a promise of any scoring outcome." },
  { id: "br-30", area: "business-reasoning", question: "A hotel restaurant loses money on weekday breakfast. Option 1 cuts weekday breakfast entirely, saving $2,400 a month. Option 2 switches it to self-serve, saving $1,500 a month after a one-off $4,000 equipment cost. Sixty percent of weekday guests are on corporate contracts that include breakfast and run for another 14 months. Which option is better supported by these facts?", choices: ["Option 2 — it keeps a service the hotel is contracted to provide for 14 more months, and its $4,000 cost is recovered in under three months of savings", "Option 1, because it saves $900 a month more", "Option 1, because cutting a loss-making service entirely is the cleanest fix", "Option 2, because self-serve is always cheaper to run than table service"], correctAnswer: "Option 2 — it keeps a service the hotel is contracted to provide for 14 more months, and its $4,000 cost is recovered in under three months of savings", explanation: "Option 1 does save more per month, but it withdraws something 60% of weekday guests are contractually entitled to for over a year, which is not the hotel's to remove. Option 2's $4,000 is recovered in under three months at $1,500 a month and leaves the obligation intact. Two of the alternatives weigh only the monthly saving, and the last states a rule these facts do not need." },

  // --- Customer relations ---
  { id: "cr-01", area: "customer-relations", question: "An angry customer's reserved product is out of stock. The BEST first move:", choices: ["Explain company policy immediately", "Apologize sincerely and acknowledge the frustration before proposing a solution", "Tell them it's not your fault", "Offer nothing"], correctAnswer: "Apologize sincerely and acknowledge the frustration before proposing a solution", explanation: "Service recovery starts with empathy and ownership; leading with policy or blame escalates the conflict." },
  { id: "cr-02", area: "customer-relations", question: "'Active listening' with a customer means:", choices: ["Waiting silently to talk", "Paraphrasing their concern back to confirm you understood", "Interrupting to give advice", "Reading a script"], correctAnswer: "Paraphrasing their concern back to confirm you understood", explanation: "Active listening confirms understanding ('So the issue is...'), which de-escalates and gets to the real problem." },
  { id: "cr-03", area: "customer-relations", question: "A loyal customer asks for a discount you can't fully give. Best response:", choices: ["Flatly say no", "Explain what you CAN offer and frame it around their value to the business", "Give away everything for free", "Ignore the request"], correctAnswer: "Explain what you CAN offer and frame it around their value to the business", explanation: "Offer the achievable alternative and tie it to the relationship — preserves goodwill without overpromising." },
  { id: "cr-04", area: "customer-relations", question: "The main goal of positive customer relations is to:", choices: ["Win one argument", "Build repeat business and loyalty over time", "Avoid all customers", "Maximize a single transaction"], correctAnswer: "Build repeat business and loyalty over time", explanation: "Customer relations is a long-game investment in retention and referrals, not winning a single interaction." },
  { id: "cr-05", area: "customer-relations", question: "A customer complaint is actually valuable because it:", choices: ["Is always unfair", "Surfaces a fixable problem and a chance to recover the relationship", "Should be ignored", "Means you should quit"], correctAnswer: "Surfaces a fixable problem and a chance to recover the relationship", explanation: "Complaints reveal issues other customers stay silent about; handled well, they increase loyalty." },
  { id: "cr-06", area: "customer-relations", question: "Which is a professional way to handle a mistake YOUR company made?", choices: ["Blame the customer", "Own it, apologize, fix it, and prevent recurrence", "Pretend it didn't happen", "Argue about who's right"], correctAnswer: "Own it, apologize, fix it, and prevent recurrence", explanation: "Ownership + fix + prevention is the professional recovery pattern; defensiveness damages the relationship." },
  { id: "cr-07", area: "customer-relations", question: "Following up after resolving an issue matters because it:", choices: ["Wastes the customer's time", "Confirms the fix worked and shows the customer they matter", "Is never done", "Annoys everyone"], correctAnswer: "Confirms the fix worked and shows the customer they matter", explanation: "Follow-up verifies resolution and signals care — a hallmark of strong customer relations." },
  { id: "cr-08", area: "customer-relations", question: "A customer is calm but confused about a product. The best approach is to:", choices: ["Use heavy jargon to sound expert", "Explain clearly in plain language and check understanding", "Rush them out", "Tell them to read the manual"], correctAnswer: "Explain clearly in plain language and check understanding", explanation: "Clear, jargon-free explanation plus a comprehension check serves the customer and builds trust." },
  { id: "cr-09", area: "customer-relations", question: "'Exceeding expectations' in service usually means:", choices: ["Doing the bare minimum", "Delivering a small, thoughtful extra beyond what was required", "Charging more", "Making the customer wait"], correctAnswer: "Delivering a small, thoughtful extra beyond what was required", explanation: "A thoughtful extra (a proactive fix, a small courtesy) turns satisfaction into loyalty and word-of-mouth." },

  // --- Marketing fundamentals ---
  { id: "mk-01", area: "marketing-fundamentals", question: "The '4 Ps' of the marketing mix are:", choices: ["Price, People, Profit, Purpose", "Product, Price, Place, Promotion", "Plan, Produce, Promote, Profit", "Product, Payment, Percent, Push"], correctAnswer: "Product, Price, Place, Promotion", explanation: "The classic marketing mix is Product, Price, Place, Promotion — the controllable levers a marketer sets." },
  { id: "mk-02", area: "marketing-fundamentals", question: "'Place' in the marketing mix refers to:", choices: ["The store's decoration", "How and where the product is distributed and made available", "The advertising budget", "The company headquarters"], correctAnswer: "How and where the product is distributed and made available", explanation: "'Place' is distribution — the channels and locations through which customers can get the product." },
  { id: "mk-03", area: "marketing-fundamentals", question: "Market positioning is about:", choices: ["The shelf a product sits on", "The distinct place a brand occupies in the customer's mind vs. competitors", "The GPS location of a store", "The size of the logo"], correctAnswer: "The distinct place a brand occupies in the customer's mind vs. competitors", explanation: "Positioning is perceptual — how customers see your brand relative to alternatives (e.g., premium vs. budget)." },
  { id: "mk-04", area: "marketing-fundamentals", question: "A 'target market' is:", choices: ["Everyone on earth", "The specific group a business aims its marketing at", "The competitor's customers only", "The sales team"], correctAnswer: "The specific group a business aims its marketing at", explanation: "Targeting focuses resources on the segment most likely to buy, rather than marketing to everyone." },
  { id: "mk-05", area: "marketing-fundamentals", question: "Which is a PROMOTION decision?", choices: ["Setting the wholesale price", "Choosing to run a social-media ad campaign", "Selecting a distributor", "Designing the product"], correctAnswer: "Choosing to run a social-media ad campaign", explanation: "Promotion covers advertising, sales promotion, PR, and personal selling — how you communicate value. The others are Price, Place, and Product." },
  { id: "mk-06", area: "marketing-fundamentals", question: "A brand's 'value proposition' is:", choices: ["Its stock price", "The clear reason a customer should choose it over alternatives", "Its number of employees", "Its office address"], correctAnswer: "The clear reason a customer should choose it over alternatives", explanation: "The value proposition states the specific benefit that makes the brand the better choice for its target." },
  { id: "mk-07", area: "marketing-fundamentals", question: "Raising price while keeping quality signals can support a strategy of:", choices: ["Bargain positioning", "Premium positioning", "Hiding the product", "Ignoring customers"], correctAnswer: "Premium positioning", explanation: "Higher price paired with quality cues positions a brand as premium; it must be backed by real perceived value." },
  { id: "mk-08", area: "marketing-fundamentals", question: "Which metric best tracks a promotion's efficiency?", choices: ["Number of employees", "Cost per acquisition (what you pay to gain one customer)", "Office square footage", "CEO's salary"], correctAnswer: "Cost per acquisition (what you pay to gain one customer)", explanation: "Cost per acquisition links spend to customers gained, showing whether the promotion is efficient." },
  { id: "mk-09", area: "marketing-fundamentals", question: "Product differentiation means:", choices: ["Making your product identical to rivals", "Giving your product distinct features/benefits that set it apart", "Lowering price only", "Copying a competitor exactly"], correctAnswer: "Giving your product distinct features/benefits that set it apart", explanation: "Differentiation creates a meaningful difference customers value, reducing head-to-head price competition." }
];

function shuffle<T>(items: T[]): T[] {
  const copy = [...items];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

export function buildDecaDrillSession(count: number, areas?: DecaDrillArea[]): DecaDrillQuestion[] {
  const pool = areas && areas.length > 0 ? DECA_DRILL_BANK.filter((q) => areas.includes(q.area)) : DECA_DRILL_BANK;
  const shuffled = shuffle(pool);
  if (count <= shuffled.length) return shuffled.slice(0, count);
  const result = [...shuffled];
  while (result.length < count) result.push(...shuffle(pool));
  return result.slice(0, count);
}

export type DecaDrillAnswer = { id: string; selected: string };
export type DecaDrillGradedItem = { id: string; area: DecaDrillArea; correct: boolean; correctAnswer: string; explanation: string };
export type DecaDrillSkillResult = { area: DecaDrillArea; skillSlug: string; label: string; total: number; correct: number; scorePercent: number; passed: boolean };
export type DecaDrillResult = { total: number; correctCount: number; scorePercent: number; items: DecaDrillGradedItem[]; perSkill: DecaDrillSkillResult[] };

export const DECA_DRILL_PASS_THRESHOLD = 70;

export function gradeDecaDrillAnswers(answers: DecaDrillAnswer[]): DecaDrillResult {
  const byId = new Map(DECA_DRILL_BANK.map((q) => [q.id, q]));
  const items: DecaDrillGradedItem[] = [];
  const areaTally = new Map<DecaDrillArea, { total: number; correct: number }>();

  for (const answer of answers) {
    const q = byId.get(answer.id);
    if (!q) continue;
    const correct = answer.selected === q.correctAnswer;
    items.push({ id: q.id, area: q.area, correct, correctAnswer: q.correctAnswer, explanation: q.explanation });
    const tally = areaTally.get(q.area) ?? { total: 0, correct: 0 };
    tally.total += 1;
    if (correct) tally.correct += 1;
    areaTally.set(q.area, tally);
  }

  const total = items.length;
  const correctCount = items.filter((i) => i.correct).length;
  const scorePercent = total > 0 ? Math.round((correctCount / total) * 100) : 0;
  const perSkill: DecaDrillSkillResult[] = Array.from(areaTally.entries()).map(([area, tally]) => {
    const meta = DECA_DRILL_AREAS.find((a) => a.id === area);
    const pct = tally.total > 0 ? Math.round((tally.correct / tally.total) * 100) : 0;
    return { area, skillSlug: meta?.skillSlug ?? "", label: meta?.label ?? area, total: tally.total, correct: tally.correct, scorePercent: pct, passed: pct >= DECA_DRILL_PASS_THRESHOLD };
  });

  return { total, correctCount, scorePercent, items, perSkill };
}

// --- Duplicate-resistant mastery evidence (M13E1D) ------------------------------------------------
//
// `gradeDecaDrillAnswers` above reports the LEARNER'S SESSION: every graded answer, counted every
// time it was submitted. That is the right number to show someone who just finished a drill, but it
// is the wrong number to persist, because `answers` is composed entirely by the client and the same
// question id may appear in it any number of times.
//
// The bypass this closes, reproduced exactly: submit five distinct performance-indicator ids with
// only ONE answered correctly, then repeat that one correct id twelve more times. The session tally
// is 13/17 = 76%, which clears the 70% threshold and would have written PRACTICING mastery — off a
// single genuinely correct question out of five. A minimum-distinct-questions floor alone does not
// stop it, because the score itself was still duplicate-weighted.
//
// So persistence reads from an EVIDENCE SET instead: at most one entry per valid question id, using
// the FIRST answer submitted for that id.
//
//   first occurrence, not last  — a later answer to an already-answered id is ignored, so revealing
//                                 the explanation and resubmitting cannot convert a miss into credit
//   first occurrence, not all   — `buildDecaDrillSession` legitimately repeats items once a session
//                                 is longer than an area's nine-item pool, so requiring every
//                                 occurrence to be correct would punish honest repeats
//   ignore, do not reject       — an unrecognised id contributes nothing rather than failing the
//                                 whole submission, and each id is attributed to its OWN bank area,
//                                 so a filtered session can never misattribute evidence
//
// This makes the evidence duplicate-resistant and unknown-id-resistant. It is NOT tamper-proof:
// nothing yet binds a submission to the question set the server actually served, so a client may
// still answer bank ids it was never shown. Session binding is deliberately out of scope here.

/**
 * Distinct valid questions required for ONE skill before any mastery or review may be written.
 *
 * Five, because each area's bank holds nine distinct items (so five is a majority of what exists),
 * five is the smallest focused-session size the UI offers, and at five questions the 70% threshold
 * needs at least four correct — there is no way to clear it on a single lucky answer.
 */
export const DECA_DRILL_REQUIRED_UNIQUE = 5;

export type DecaDrillEvidenceStatus = "insufficient-evidence" | "below-threshold" | "passing";

export type DecaDrillSkillEvidence = {
  area: DecaDrillArea;
  skillSlug: string;
  label: string;
  /** Distinct valid question ids submitted for this skill. */
  uniqueTotal: number;
  /** How many of those were correct ON THEIR FIRST submitted answer. */
  uniqueCorrect: number;
  requiredUnique: number;
  /** `uniqueCorrect / uniqueTotal` — the only score that may reach the database. */
  evidenceScore: number;
  evidenceStatus: DecaDrillEvidenceStatus;
  /** True only with enough distinct questions AND an evidence score at or above the threshold. */
  passed: boolean;
};

/** Build the per-skill evidence set for a submission. Pure; deterministic; order-independent. */
export function buildDecaDrillEvidence(answers: DecaDrillAnswer[]): DecaDrillSkillEvidence[] {
  const byId = new Map(DECA_DRILL_BANK.map((q) => [q.id, q]));

  // First occurrence per valid id wins; unknown ids and every repeat are dropped here.
  const firstById = new Map<string, { question: DecaDrillQuestion; selected: string }>();
  for (const answer of answers) {
    const question = byId.get(answer.id);
    if (!question) continue;
    if (firstById.has(answer.id)) continue;
    firstById.set(answer.id, { question, selected: answer.selected });
  }

  const tally = new Map<DecaDrillArea, { uniqueTotal: number; uniqueCorrect: number }>();
  for (const { question, selected } of firstById.values()) {
    // Attribution is by the question's OWN area, never by whatever area the session requested.
    const bucket = tally.get(question.area) ?? { uniqueTotal: 0, uniqueCorrect: 0 };
    bucket.uniqueTotal += 1;
    if (selected === question.correctAnswer) bucket.uniqueCorrect += 1;
    tally.set(question.area, bucket);
  }

  return Array.from(tally.entries()).map(([area, bucket]) => {
    const meta = DECA_DRILL_AREAS.find((a) => a.id === area);
    const evidenceScore = bucket.uniqueTotal > 0 ? Math.round((bucket.uniqueCorrect / bucket.uniqueTotal) * 100) : 0;
    const evidenceStatus: DecaDrillEvidenceStatus =
      bucket.uniqueTotal < DECA_DRILL_REQUIRED_UNIQUE
        ? "insufficient-evidence"
        : evidenceScore >= DECA_DRILL_PASS_THRESHOLD
          ? "passing"
          : "below-threshold";
    return {
      area,
      skillSlug: meta?.skillSlug ?? "",
      label: meta?.label ?? area,
      uniqueTotal: bucket.uniqueTotal,
      uniqueCorrect: bucket.uniqueCorrect,
      requiredUnique: DECA_DRILL_REQUIRED_UNIQUE,
      evidenceScore,
      evidenceStatus,
      passed: evidenceStatus === "passing"
    };
  });
}

/**
 * What to persist for one skill, or `null` meaning DO NOT CALL the persistence helper at all.
 *
 * `null` is not "write a zero" — it is the absence of a call, so a short submission cannot write
 * mastery, cannot schedule a review, and cannot knock an existing mastery down through a due
 * review it never earned the right to answer.
 */
export function decaDrillPersistenceRequest(evidence: DecaDrillSkillEvidence): { scorePercent: number; passed: boolean } | null {
  if (evidence.uniqueTotal < evidence.requiredUnique) return null;
  return { scorePercent: evidence.evidenceScore, passed: evidence.passed };
}
